FROM node:alpine

WORKDIR /api

COPY . /api

EXPOSE 8081

RUN npm install

RUN npm install -g cors

RUN npm install -g nodemon

RUN npm install -g express

RUN npm install -g pg

CMD ["npm run","migrate:rollback"]

CMD ["npm run","migrate:latest"]

CMD ["npm run","seed:run"]

CMD ["nodemon", "./app.js"]